export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  ANALYSIS: '/analysis',
  DATA_SOURCES: '/data-sources',
  DEEP_INSIGHT: '/deep-insight',
  REPORTS: '/reports',
  PRICING: '/pricing',
  ACCOUNT: '/account',
  SUPPORT: '/support',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_USERS: '/admin/users',
  ADMIN_REVENUE: '/admin/revenue',
  ADMIN_FEEDBACKS: '/admin/feedbacks',
  ADMIN_SETTINGS: '/admin/settings',
}
