spring:
  application:
    name: researchco-backend
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require&preferQueryMode=simple&prepareThreshold=0
    username: postgres.kbxulunixssiykelahpz
    password: Nguyenhoang@0712
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: always

server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8

app:
  jwt:
    secret: 56737450-04d2-4593-922a-c5c29b528799
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}

integration:
  youtube:
    api-key: ${YOUTUBE_API_KEY:AIzaSyCg6R0ttPTY7jBhWa5m3LrkqjpgXaAH_uk}
    max-results: ${YOUTUBE_MAX_RESULTS:5}
